# JYSK Stock & Price Monitoring Configuration

# Browser settings
headless: true  # Set to true for production, false for testing
timeout_ms: 30000
check_frequency: "7d"

# Store configuration with stock thresholds
stores:
  - name: "JYSK Viva Park, Casablanca"
    stock_threshold: 6
  - name: "JYSK Aeria Mall, Casablanca"
    stock_threshold: 8

# Price monitoring settings
price_monitoring:
  enabled: true
  price_change_threshold_percent: 1

# Alert configuration
alerts:
  min_hours_between_same_alert: 12
  telegram:
    enabled: true
    bot_token: ""   # leave empty; GitHub Secrets override
    chat_id: ""     # leave empty; GitHub Secrets override
