name: JYSK monitor (weekly)

on:
  schedule:
    # Weekly — Sunday 22:00 Casablanca (~ UTC+1) → run 21:00 UTC
    - cron: "0 21 * * 0"
  workflow_dispatch: {}  # allow manual "Run workflow"

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      # Import products into the (ephemeral) DB each run
      - name: Import products
        run: python app.py import-csv products.csv

      - name: Run monitor once
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python app.py run-once

      # ✅ Heartbeat: always send a Telegram test so we can verify secrets work
      - name: Send Telegram heartbeat
        if: always()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - << 'PY'
          import os, requests, sys
          t=os.environ.get("TELEGRAM_BOT_TOKEN"); c=os.environ.get("TELEGRAM_CHAT_ID")
          if not t or not c:
              print("Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID"); sys.exit(1)
          r=requests.post(f"https://api.telegram.org/bot{t}/sendMessage",
                          json={"chat_id": c, "text": "✅ GitHub Actions: run completed (heartbeat)"})
          print("HTTP", r.status_code, r.text[:200]); r.raise_for_status()
          PY

      # Always upload any debug screenshots/HTML if they exist
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            debug_*.png
            debug_*.html
          if-no-files-found: ignore
