name: JYSK monitor (weekly)

on:
  schedule:
    # Weekly — Sunday 22:00 Casablanca (~ UTC+1) → run 21:00 UTC
    - cron: "0 21 * * 0"
  workflow_dispatch: {}  # allow manual "Run workflow"

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install Chromium + Linux deps for Playwright
          python -m playwright install --with-deps chromium

      # Import products into the (ephemeral) DB each run
      - name: Import products
        run: python app.py import-csv products.csv

      - name: Run monitor once
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python app.py run-once

      # Always upload any debug screenshots/HTML if they exist
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug
          path: |
            debug_*.png
            debug_*.html
          if-no-files-found: ignore
